#!/bin/sh

. $(dirname $0)/ec2.rc

ec2_eni_id=$(declare | grep 'eni-[a-z0-9]' | grep '^ec2' | cut -f2 -d'=')
export ec2_eni_id

add_ec2_secondary_private_ip ()
{
    local _iface=$1
    local _ip=$2

    ## EC2 related
    local_ip=$(ip addr show dev $_iface | grep inet | grep -v secondary | awk {'print $2'} | cut -f1 -d'/')

    ## If local ip and ec2 ip mis-match for the given instance exit gracefully.
    [ "$local_ip" != "$ec2_local_ipv4" ] && {
         echo "ERROR: Local ip and ec2 ip are mismatching.. exiting script"
         exit 0
    }
    ec2-assign-private-ip-addresses --network-interface $ec2_eni_id --secondary-private-ip-address $_ip
}

delete_ec2_secondary_private_ip ()
{
    local _iface=$1
    local _ip=$2

    ## EC2 related
    local_ip=$(ip addr show dev $_iface | grep inet | grep -v secondary | awk {'print $2'} | cut -f1 -d'/')

    ## If local ip and ec2 ip mis-match for the given instance exit gracefully.
    [ "$local_ip" != "$ec2_local_ipv4" ] && {
         echo "ERROR: Local ip and ec2 ip are mismatching.. exiting script"
         exit 0
    }
    ec2-unassign-private-ip-addresses --network-interface $ec2_eni_id --secondary-private-ip-address $_ip
}