#!/bin/sh
#
# Copyright (C) 2013 Red Hat, Inc. <http://www.redhat.com>
#
# Author: Harshavardhana <fharshav@redhat.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <http://www.gnu.org/licenses/>.

. $(dirname $0)/ec2.rc

ec2_eni_id=$(declare | grep 'eni-[a-z0-9]' | grep '^ec2' | cut -f2 -d'=')
export ec2_eni_id

add_ec2_secondary_private_ip ()
{
    local _iface=$1
    local _ip=$2

    ## EC2 related
    local_ip=$(ifconfig $_iface | grep 'inet addr:' | awk {'print $2'} | cut -f2 -d:)

    ## If local ip and ec2 ip mis-match for the given instance exit gracefully.
    [ "$local_ip" != "$ec2_local_ipv4" ] && {
         echo "ERROR: Local ip and ec2 ip are mismatching.. exiting script"
         exit 0
    }
    ec2-assign-private-ip-addresses --network-interface $ec2_eni_id --secondary-private-ip-address $_ip
}

delete_ec2_secondary_private_ip ()
{
    local _iface=$1
    local _ip=$2

    ## EC2 related
    local_ip=$(ifconfig $_iface | grep 'inet addr:' | awk {'print $2'} | cut -f2 -d:)

    ## If local ip and ec2 ip mis-match for the given instance exit gracefully.
    [ "$local_ip" != "$ec2_local_ipv4" ] && {
         echo "ERROR: Local ip and ec2 ip are mismatching.. exiting script"
         exit 0
    }
    ec2-unassign-private-ip-addresses --network-interface $ec2_eni_id --secondary-private-ip-address $_ip
}